### ISSUE TITLE
`fail on too small number of file descriptors`

### ISSUE THREAD

**Issue by haolian9** [cloudalchemy/ansible-fluentd#35]
Actually, the machine says:

```
$ ulimit -n
100001
```

Then, I changed `file_descriptors.stdout < "1025"` to `file_descriptors.stdout < 1025`, it works as expected

**Comment by paulfantom** [comment]
I don't see how this relates to this role. It looks more like fluentd bug, have you tried asking in https://github.com/fluent/fluentd?

Just to confirm, @jkrol2 we are not touching file descriptor system settings, are we?

**Comment by haolian9** [comment]
plz see the related lines [here](https://github.com/cloudalchemy/ansible-fluentd/blob/master/tasks/preflight.yml#L22-L25)

It just an assertion.
